kind: PersistentVolume
apiVersion: v1
metadata:
  name: openblog-db-pv
  namespace: openblog
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/openblog-db-pv

