kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openblog-db-pvc
  namespace: openblog
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: openblog-db-pv
